import { Inter } from "next/font/google";
import Header from "./components/header/Header";
import styles from "./layout.module.scss";

import { Providers } from "./store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Header />
        <Providers>
          <main className={inter.className}>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
